
/* ================================================================ *
 *          Automatically generated by n-Blocks Studio 2.0          *
 *                                                                  *
 *                         www.n-blocks.net                         *
 * ================================================================ */
#include "nlib\nblocks.h"
#include "nlib\BSP\bsp.h"
// Custom nodes:
#include "nlib\nRF5xRadio\nrf5xradio.h"
#include "nlib\StringSerial\stringserial.h"

// -*-*- List of node objects -*-*-
nBlock_nRF5xRadio        nb_nBlockNode0_nRF5xRadio   (RADIO_MODE_RX_ONLY, RADIO_RATE_2M, 2, 20, 0xC0, 0x55, 0x42, 0xBB, 0xC2);
nBlock_StringSerial      nb_nBlockNode1_StringSerial (P0_31, P0_2);

// -*-*- List of connection objects -*-*-
nBlockConnection    n_conn0( &nb_nBlockNode0_nRF5xRadio,   0,    &nb_nBlockNode1_StringSerial, 0);


// -*-*- Main function -*-*-
int main(void) {
    SetupWorkbench();
    while(1) {
        ProgressNodes();
        
        // Your custom code here!
    }
}
